// The branding images are generated by scripts/generate-branding.py and read
// at run time by file name, so a renamed or missing file fails only in a
// packaged build. These checks read the shipped files and the code naming them.
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const root = path.join(__dirname, "..");
const read = (file: string) => fs.readFileSync(path.join(root, file));

// PNG width, height and colour type from the IHDR chunk.
function pngInfo(file: string): { width: number; height: number; alpha: boolean } {
  const png = read(file);
  expect(png.subarray(1, 4).toString("ascii")).toBe("PNG");
  return { width: png.readUInt32BE(16), height: png.readUInt32BE(20), alpha: png[25] === 6 };
}

describe("branding assets", () => {
  it("ships every tray icon src/tray.ts names, at 1x and 2x", () => {
    const tray = read("src/tray.ts").toString();
    const names = [...tray.matchAll(/"(hydra[A-Za-z-]*)\.png"/g)].map((m) => m[1]);
    expect(names.sort()).toEqual(
      ["hydra-tray", "hydra-tray-dark", "hydra-tray-light", "hydra-tray-outline", "hydraTemplate"].sort(),
    );
    for (const name of names) {
      const base = name === "hydraTemplate" ? 16 : 24;
      expect(pngInfo(`assets/icons/${name}.png`)).toEqual({ width: base, height: base, alpha: true });
      expect(pngInfo(`assets/icons/${name}@2x.png`)).toEqual({ width: base * 2, height: base * 2, alpha: true });
    }
  });

  it("unpacks the logo and the splash image the windows load", () => {
    const pkg = JSON.parse(read("package.json").toString()) as {
      build: { asarUnpack: string[]; files: string[] };
    };
    for (const file of ["assets/hydra-logo.png", "assets/hydra-splash.png"]) {
      expect(pkg.build.asarUnpack).toContain(file);
      expect(pngInfo(file)).toEqual({ width: 256, height: 256, alpha: true });
    }
    expect(read("assets/about.html").toString()).toContain('src="hydra-logo.png"');
    expect(read("assets/splash.html").toString()).toContain('src="hydra-splash.png"');
    // The 2048 pixel sources and masters stay out of the package.
    expect(pkg.build.files).toContain("!assets/branding/**");
  });

  it("gives every Linux app icon transparent rounded corners", () => {
    for (const size of [16, 24, 32, 48, 64, 128, 256, 512]) {
      expect(pngInfo(`build/icons/${size}x${size}.png`)).toEqual({ width: size, height: size, alpha: true });
    }
    expect(pngInfo("build/icon.png")).toEqual({ width: 1024, height: 1024, alpha: true });
  });

  it("paints the splash window and page the same dark colour", () => {
    expect(read("src/main.ts").toString()).toContain('backgroundColor: "#0A121F"');
    const splash = read("assets/splash.html").toString();
    expect(splash).toMatch(/html, body \{\s*background: #0A121F;/);
    expect(splash).toContain("border-top-color: #12C9A5;");
    expect(splash).toMatch(/\.loading-text \{\s*color: #12C9A5;/);
  });
});
